//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Export_to_Excel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int empid { get; set; }
        public string Name { get; set; }
        public System.DateTime DOJ { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Salary { get; set; }
    }
}
